### ISSUE TITLE
Hound installation problem on Windows 7 box. 

### ISSUE THREAD

**Issue by adipan** [etsy/Hound#123]
Hound installation problem on Windows 7 box. I understand that Hound team knows of this and does not officially support Windows.

I installed go for the first time in my life. Set GOPATH properly. I followed the quick start guide and typed -
go get github.com/etsy/hound/cmd/...

It throws following lines in my command line and also does not install binaries - houndd and hound in my GOPATH that are expected to be present at the end of installation.

# github.com/etsy/hound/ansi
src\github.com\etsy\hound\ansi\tty.go:11: undefined: syscall.Termios
src\github.com\etsy\hound\ansi\tty.go:13: undefined: syscall.SYS_IOCTL
src\github.com\etsy\hound\ansi\tty.go:15: undefined: ioctlReadTermios
src\github.com\etsy\hound\ansi\tty.go:19: not enough arguments in call to syscall.Syscall6
# github.com/etsy/hound/codesearch/index
src\github.com\etsy\hound\codesearch\index\mmap_windows.go:24: too few values in struct initializer
src\github.com\etsy\hound\codesearch\index\mmap_windows.go:26: cannot use f.Fd() (type uintptr) as type syscall.Handle in argument to syscall.CreateFileMapping
src\github.com\etsy\hound\codesearch\index\mmap_windows.go:36: too few values in struct initializer
src\github.com\etsy\hound\codesearch\index\read.go:426: undefined: syscall.Munmap
src\github.com\etsy\hound\codesearch\index\write.go:250: undefined: syscall.Munmap

**Comment by jklein** [comment]
There are a couple of PRs for windows support, #122 and #56 - not sure what the status is of those but I think at this point without those merged Hound isn't going to work on Windows. @kellegous have you looked at those PRs recently?

**Comment by ameerkat** [comment]
@adipan I'm not sure about the binary installation or what the command go install is supposed to do, I ended up calling into houndd from the root directory where I placed the config.json. You could probably get it working some other way. In any case I got it working on windows 8.1 with the changes in #122  which is coming from here https://github.com/ameerkat/Hound if you want to try it for yourself.

![image](https://cloud.githubusercontent.com/assets/389946/7781839/2cb4f99e-00ae-11e5-9c00-619820f03207.png)

**Comment by kellegous** [comment]
Hound should be building on Windows now.
